services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://vk:password@db:5432/containers
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  pinger:
    build: ./pinger
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vk
      POSTGRES_PASSWORD: password
      POSTGRES_DB: containers
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
